apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-services
  labels:
    app: services
spec:
  replicas: 1
  selector:
    matchLabels:
            app: services
  template:
    metadata:
      labels:
        app: services
    spec:
      
      volumes:
        - name: vol
          emptyDir: {}

      containers:

        - image: nginx-server:v1
          name: nginx-server
          volumeMounts:
            - name: vol
              mountPath: /www_test/
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443

        - image: mysql-server:v1
          name: mysql-server
          imagePullPolicy: Never
        
        - image: test:v1
          name: test
          volumeMounts:
            - name: vol
              mountPath: /hello/
          imagePullPolicy: Never
