apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      containers:
      - name: grafana
        image: grafana:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: abcd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.64.52  
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
