apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:v1
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        env:
        - name: SSH_USER
          value: user
        - name: SSH_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: abcd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.64.22  
  selector:
    app: nginx
  ports:
    - name: http
      port: 80          #port number within cluster
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443         #port number within cluster
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 22          #port number within cluster
      protocol: TCP
      targetPort: 22
