apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      volumes:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:v1
        imagePullPolicy: Never
        ports:
        # this should probably change to 80
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: '3306'
        - name: DB_USER
          value: wordpress_user
        - name: DB_PASSWORD
          value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: abcd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.64.52  
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      port: 5000
      # targetPort: 5000
      targetPort: 80
