apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:v1
        imagePullPolicy: Never
        #ports:
        #- containerPort: 4999
        volumeMounts:
        - name: docker-daemon
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: docker-daemon
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: abcd
spec:
  #type: LoadBalancer
  #loadBalancerIP: 192.168.64.52  
  selector:
    app: telegraf
  ports:
  - port: 4999
  #targetPort: 4999
