apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
      containers:
      - name: php
        image: php:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  type: NodePort
  selector:
    app: php
  ports:
    - name: php
      port: 5000
      targetPort: 5000
