apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 4999
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  type: NodePort
  selector:
    app: telegraf
  ports:
  - protocol: TCP
    port: 4999
    targetPort: 4999
