apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      volumes:
      - name: wp-storage
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wp
        image: wp:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: wp
        env:
        - name: WP_DB_USER
          value: root
        - name: WP_DB_PASSWORD
          value: password
        - name: WP_DB_HOST
          value: mysql
        volumeMounts:
        - name: wp-storage
          mountPath: /wp_files
---
apiVersion: v1
kind: Service
metadata:
  name: wp
  labels:
    app: wp
spec:
  type: NodePort
  selector:
    app: wp
  ports:
    - name: wp
      protocol: TCP
      port: 5050
      targetPort: 80
